export const CORE_TOKENS = {
  color: {
    surfacePage: '#F7F7F7',
    surfaceCard: '#FFFFFF',
    surfaceMuted: '#F2F2F2',
    surfaceElevated: '#FFFFFF',
    borderSubtle: 'rgba(0,0,0,0.07)',
    borderWeak: 'rgba(0,0,0,0.12)',
    divider: 'rgba(0,0,0,0.2)',
    textPrimary: '#000000',
    textSecondary: 'rgba(0,0,0,0.5)',
    textTertiary: 'rgba(0,0,0,0.35)',
    textInverted: '#FFFFFF',
    brandPrimary: '#809DE4',
    brandPrimaryStrong: '#007CFF',
    brandAccentBlue: '#3482FF',
    switchOnGreen: '#0CCE94',
    brandPrimarySoft: 'rgba(128,157,228,0.12)',
    buttonUnselectedBg: 'rgba(0,0,0,0.06)',
    switchOff: 'rgba(0,0,0,0.1)',
    shadowColor: '#000000',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 21,
    card: 20,
    full: 999,
  },
  size: {
    switchTrackWidth: 50,
    switchTrackHeight: 28,
    switchThumb: 20,
    circleButton: 46,
    iconMd: 20,
    pageSwitchHeight: 37,
    pageSwitchRadius: 30,
    sliderTrackHeight: 28,
    sliderThumb: 20,
  },
  typography: {
    titleXL: 28,
    titleLG: 21,
    titleMD: 16,
    bodyMD: 14,
    bodySM: 13,
    caption: 12,
    micro: 10,
  },
  motion: {
    fast: 140,
    normal: 180,
    slow: 260,
    springTension: 90,
    springFriction: 12,
  },
  zIndex: {
    base: 0,
    floating: 3,
    overlay: 10,
    modal: 20,
  },
} as const;

export const COMPONENT_TOKENS = {
  controlTitle: {
    height: 28,
    centerHeight: 20,
    centerHeightWithSubtitle: 44,
    dividerWidth: 1,
    dividerHeight: 12,
    rightPillPaddingH: 12,
    rightPillPaddingV: 5.5,
  },
  pageSwitch: {
    height: CORE_TOKENS.size.pageSwitchHeight,
    paddingH: 16,
    borderRadius: CORE_TOKENS.size.pageSwitchRadius,
    borderWidthSelected: 1.75,
    borderWidthDefault: 1,
    textSize: 14,
  },
  circleButton: {
    cardBackgroundColor: CORE_TOKENS.color.surfaceCard,
    cardBorderRadius: CORE_TOKENS.radius.card,
    cardPaddingHorizontal: CORE_TOKENS.spacing.sm,
    cardPaddingVertical: CORE_TOKENS.spacing.lg,
    itemPadding: CORE_TOKENS.spacing.xs,
    itemLabelGap: CORE_TOKENS.spacing.sm,
    rowSplitPadding: CORE_TOKENS.spacing.lg,
    buttonSize: 44,
    buttonRadius: CORE_TOKENS.radius.full,
    buttonSelectedBackgroundColor: CORE_TOKENS.color.brandPrimary,
    buttonUnselectedBackgroundColor: CORE_TOKENS.color.buttonUnselectedBg,
    iconSize: CORE_TOKENS.size.iconMd,
    iconSelectedColor: CORE_TOKENS.color.textInverted,
    iconUnselectedColor: CORE_TOKENS.color.textPrimary,
    labelFontSize: CORE_TOKENS.typography.bodySM,
    labelLineHeight: CORE_TOKENS.typography.bodySM,
    labelFontWeight: '500',
    labelColor: CORE_TOKENS.color.textPrimary,
    maxColumns: 4,
    minCount: 2,
    maxCount: 8,
  },
  squareButton: {
    minCount: 2,
    maxCount: 8,
    maxColumns: 4,
    rowSplitPadding: CORE_TOKENS.spacing.lg,
    iconSize: CORE_TOKENS.size.iconMd,
    iconScale: 1,
    labelFontSize: CORE_TOKENS.typography.bodySM,
    labelLineHeight: CORE_TOKENS.typography.bodySM,
    labelFontWeight: '500',
    labelSelectedColor: CORE_TOKENS.color.textInverted,
    labelUnselectedColor: CORE_TOKENS.color.textPrimary,
    iconSelectedColor: CORE_TOKENS.color.textInverted,
    iconUnselectedColor: CORE_TOKENS.color.textPrimary,
    compactLabelColor: 'rgba(0,0,0,0.8)',
    compactIconColor: 'rgba(0,0,0,0.8)',
    itemLabelGap: CORE_TOKENS.spacing.sm,
    itemPaddingHorizontal: CORE_TOKENS.spacing.sm,
    itemPaddingTop: CORE_TOKENS.spacing.md,
    itemPaddingBottom: CORE_TOKENS.spacing.sm,
    cardPadding: CORE_TOKENS.spacing.lg,
    largeContainerBackgroundColor: CORE_TOKENS.color.surfaceCard,
    largeContainerRadius: CORE_TOKENS.radius.card,
    largeContainerPadding: CORE_TOKENS.spacing.xs,
    largeItemRadius: CORE_TOKENS.radius.lg,
    largeItemUnselectedBackgroundColor: CORE_TOKENS.color.buttonUnselectedBg,
    compactTrackBackgroundColor: CORE_TOKENS.color.buttonUnselectedBg,
    compactTrackRadius: CORE_TOKENS.radius.lg,
    compactTrackPadding: 3,
    compactItemRadius: 14,
    compactSelectedBackgroundColor: CORE_TOKENS.color.surfaceCard,
    compactSelectedShadowColor: CORE_TOKENS.color.shadowColor,
    compactSelectedShadowOpacity: 0.02,
    compactSelectedShadowRadiusLg: 12,
    compactSelectedShadowOffsetLgY: 4,
    compactSelectedElevation: 1,
    selectedColorDefault: CORE_TOKENS.color.brandPrimary,
  },
  switchRow: {
    containerRadius: CORE_TOKENS.radius.card,
    containerPaddingHorizontal: 16,
    containerPaddingVertical: 12,
    contentGap: CORE_TOKENS.spacing.sm,
    titleFontSize: CORE_TOKENS.typography.titleMD,
    titleFontWeight: '500',
    titleColor: CORE_TOKENS.color.textPrimary,
    subtitleFontSize: CORE_TOKENS.typography.bodySM,
    subtitleFontWeight: '400',
    subtitleColor: CORE_TOKENS.color.textSecondary,
    leftIconContainerSize: 24,
    leftIconSize: CORE_TOKENS.size.iconMd,
    titleRightIconSize: 16,
    titleRightIconGap: CORE_TOKENS.spacing.xs,
    titleRightIconColor: CORE_TOKENS.color.textTertiary,
    titleRightIconStrokeWidth: 1.5,
    rightButtonSize: 40,
    rightButtonRadius: CORE_TOKENS.radius.full,
    rightButtonOnBackgroundColor: CORE_TOKENS.color.brandAccentBlue,
    rightButtonOffBackgroundColor: CORE_TOKENS.color.surfaceMuted,
    rightButtonIconSize: CORE_TOKENS.size.iconMd,
    rightButtonIconOnColor: CORE_TOKENS.color.textInverted,
    rightButtonIconOffColor: CORE_TOKENS.color.textPrimary,
    switchTrackWidth: CORE_TOKENS.size.switchTrackWidth,
    switchTrackHeight: 32,
    switchTrackInnerHeight: CORE_TOKENS.size.switchTrackHeight,
    switchTrackRadius: CORE_TOKENS.radius.full,
    switchTrackOnBackgroundColor: CORE_TOKENS.color.switchOnGreen,
    switchTrackOffBackgroundColor: CORE_TOKENS.color.switchOff,
    switchTrackPaddingHorizontal: CORE_TOKENS.spacing.xs,
    switchThumbSize: CORE_TOKENS.size.switchThumb,
    switchThumbRadius: CORE_TOKENS.radius.full,
    switchThumbColor: CORE_TOKENS.color.surfaceElevated,
  },
  circleButtonGroup: {
    itemWidth: 46,
    itemHeight: 69,
  },
  slider: {
    dotSize: 6,
    centerDividerHeight: 8,
    edgeLabelSize: 10,
    tickLabelSize: 10,
  },
  page: {
    paddingH: 16,
    paddingV: 24,
    equipmentPaddingTop: 20,
    equipmentPaddingVertical: 100,
  },
} as const;

// 兼容 1.0 命名，便于分阶段迁移；2.0 新代码优先使用 CORE_TOKENS / COMPONENT_TOKENS。
export const TOKENS = {
  colors: {
    pageBg: CORE_TOKENS.color.surfacePage,
    cardBg: CORE_TOKENS.color.surfaceCard,
    borderAccent: '#FF0000',
    textPrimary: CORE_TOKENS.color.textPrimary,
    subtitleText: 'rgba(0,0,0,0.5)',
    divider: 'rgba(0,0,0,0.2)',
    rightPillBg: 'rgba(0,0,0,0.06)',
    rightText: 'rgba(0,0,0,0.8)',
    mainColor: CORE_TOKENS.color.brandPrimary,
    switchOff: CORE_TOKENS.color.switchOff,
    switchThumb: CORE_TOKENS.color.surfaceElevated,
    circleUnselectedBg: CORE_TOKENS.color.surfaceMuted,
    pageSwitchSelectedBorder: CORE_TOKENS.color.brandPrimaryStrong,
    pageSwitchUnselectedBorder: CORE_TOKENS.color.borderSubtle,
    pageSwitchText: '#666666',
  },
  spacing: {
    pagePaddingH: COMPONENT_TOKENS.page.paddingH,
    pagePaddingV: COMPONENT_TOKENS.page.paddingV,
    containerPaddingH: 0,
    containerPaddingV: 0,
    itemGap: 24,
    cardInnerPaddingH: 14,
    cardInnerPaddingV: 12,
    titleGap: 8,
    leftGroupMarginRight: 8,
    centerSubtitleMarginTop: 4,
    rightPillPaddingH: COMPONENT_TOKENS.controlTitle.rightPillPaddingH,
    rightPillPaddingV: COMPONENT_TOKENS.controlTitle.rightPillPaddingV,
    switchTrackPaddingH: 4,
    circleButtonLabelMarginTop: 4,
    pageSwitchPillPaddingH: COMPONENT_TOKENS.pageSwitch.paddingH,
    equipmentPaddingTop: COMPONENT_TOKENS.page.equipmentPaddingTop,
    equipmentPaddingVertical: COMPONENT_TOKENS.page.equipmentPaddingVertical,
  },
  radius: {
    card: CORE_TOKENS.radius.lg,
    pill: CORE_TOKENS.radius.full,
    circle: CORE_TOKENS.radius.full,
    pageSwitchPill: COMPONENT_TOKENS.pageSwitch.borderRadius,
  },
  sizes: {
    controlTitleHeight: COMPONENT_TOKENS.controlTitle.height,
    controlTitleCenterHeight: COMPONENT_TOKENS.controlTitle.centerHeight,
    controlTitleCenterHeightWithSubtitle: COMPONENT_TOKENS.controlTitle.centerHeightWithSubtitle,
    switchTrackWidth: CORE_TOKENS.size.switchTrackWidth,
    switchThumbSize: CORE_TOKENS.size.switchThumb,
    dividerWidth: COMPONENT_TOKENS.controlTitle.dividerWidth,
    dividerHeight: COMPONENT_TOKENS.controlTitle.dividerHeight,
    circleButtonSize: CORE_TOKENS.size.circleButton,
    circleButtonIconSize: CORE_TOKENS.size.iconMd,
    circleButtonItemWidth: COMPONENT_TOKENS.circleButtonGroup.itemWidth,
    circleButtonItemHeight: COMPONENT_TOKENS.circleButtonGroup.itemHeight,
    switchCardHeight: 80,
    pageSwitchPillHeight: COMPONENT_TOKENS.pageSwitch.height,
  },
  fontSize: {
    ExtraLarge: CORE_TOKENS.typography.titleXL,
    large: CORE_TOKENS.typography.titleMD,
    medium: CORE_TOKENS.typography.bodySM,
    small: CORE_TOKENS.typography.caption,
    pageSwitchPill: COMPONENT_TOKENS.pageSwitch.textSize,
  },
  motion: CORE_TOKENS.motion,
} as const;
