// 设计 tokens：统一颜色、间距、圆角等基础变量，便于全局维护
export const TOKENS = {
  colors: {
    pageBg: '#F7F7F7FF',
    cardBg: '#FFFFFFFF',
    borderAccent: '#FF0000FF',
    textPrimary: '#000000FF',
    subtitleText: '#00000080',
    divider: '#00000033',
    rightPillBg: '#0000000F',
    rightText: '#000000CC',
    mainColor: '#809DE4FF',
    switchOff: '#0000001A',
    switchThumb: '#FFFFFFFF',
    circleUnselectedBg: '#F2F2F2FF',
  },
  spacing: {
    pagePaddingH: 16,
    pagePaddingV: 24,
    containerPaddingH: 0,
    containerPaddingV: 0,
    itemGap: 24,
    cardInnerPaddingH: 16,
    cardInnerPaddingV: 12,
    titleGap: 8,
    leftGroupMarginRight: 8,
    centerSubtitleMarginTop: 4,
    rightPillPaddingH: 12,
    rightPillPaddingV: 5.5,
    switchTrackPaddingH: 4,
    circleButtonLabelMarginTop: 4,
  },
  radius: {
    card: 16,
    pill: 999,
    circle: 999,
  },
  sizes: {
    controlTitleHeight: 28,
    controlTitleCenterHeight: 20,
    controlTitleCenterHeightWithSubtitle: 44,
    switchTrackWidth: 50,
    switchThumbSize: 20,
    dividerWidth: 1,
    dividerHeight: 12,
    circleButtonSize: 46,
    circleButtonIconSize: 20,
    circleButtonItemWidth: 46,
    circleButtonItemHeight: 69,
  },
  fontSize: {
    large: 20,
    medium: 14,
    small: 12,
  },
} as const;
