export const CORE_TOKENS = {
  color: {
    surfacePage: '#F7F7F7',
    surfaceCard: '#FFFFFF',
    surfaceMuted: '#F2F2F2',
    surfaceElevated: '#FFFFFF',
    borderSubtle: 'rgba(0,0,0,0.07)',
    borderWeak: 'rgba(0,0,0,0.12)',
    divider: 'rgba(0,0,0,0.2)',
    textPrimary: '#000000',
    textSecondary: 'rgba(0,0,0,0.5)',
    textTertiary: 'rgba(0,0,0,0.35)',
    textInverted: '#FFFFFF',
    brandPrimary: '#809DE4',
    brandPrimaryStrong: '#007CFF',
    brandPrimarySoft: 'rgba(128,157,228,0.12)',
    switchOff: 'rgba(0,0,0,0.1)',
    shadowColor: '#000000',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 21,
    full: 999,
  },
  size: {
    switchTrackWidth: 50,
    switchTrackHeight: 28,
    switchThumb: 20,
    circleButton: 46,
    iconMd: 20,
    pageSwitchHeight: 37,
    pageSwitchRadius: 30,
    sliderTrackHeight: 28,
    sliderThumb: 20,
  },
  typography: {
    titleXL: 28,
    titleLG: 21,
    titleMD: 16,
    bodyMD: 14,
    bodySM: 13,
    caption: 12,
    micro: 10,
  },
  motion: {
    fast: 140,
    normal: 180,
    slow: 260,
    springTension: 90,
    springFriction: 12,
  },
  zIndex: {
    base: 0,
    floating: 3,
    overlay: 10,
    modal: 20,
  },
} as const;

export const COMPONENT_TOKENS = {
  controlTitle: {
    height: 28,
    centerHeight: 20,
    centerHeightWithSubtitle: 44,
    dividerWidth: 1,
    dividerHeight: 12,
    rightPillPaddingH: 12,
    rightPillPaddingV: 5.5,
  },
  pageSwitch: {
    height: CORE_TOKENS.size.pageSwitchHeight,
    paddingH: 16,
    borderRadius: CORE_TOKENS.size.pageSwitchRadius,
    borderWidthSelected: 1.75,
    borderWidthDefault: 1,
    textSize: 14,
  },
  circleButtonGroup: {
    itemWidth: 46,
    itemHeight: 69,
  },
  slider: {
    dotSize: 6,
    centerDividerHeight: 8,
    edgeLabelSize: 10,
    tickLabelSize: 10,
  },
  page: {
    paddingH: 16,
    paddingV: 24,
    equipmentPaddingTop: 20,
    equipmentPaddingVertical: 100,
  },
} as const;

// 兼容 1.0 命名，便于分阶段迁移；2.0 新代码优先使用 CORE_TOKENS / COMPONENT_TOKENS。
export const TOKENS = {
  colors: {
    pageBg: CORE_TOKENS.color.surfacePage,
    cardBg: CORE_TOKENS.color.surfaceCard,
    borderAccent: '#FF0000',
    textPrimary: CORE_TOKENS.color.textPrimary,
    subtitleText: 'rgba(0,0,0,0.5)',
    divider: 'rgba(0,0,0,0.2)',
    rightPillBg: 'rgba(0,0,0,0.06)',
    rightText: 'rgba(0,0,0,0.8)',
    mainColor: CORE_TOKENS.color.brandPrimary,
    switchOff: CORE_TOKENS.color.switchOff,
    switchThumb: CORE_TOKENS.color.surfaceElevated,
    circleUnselectedBg: CORE_TOKENS.color.surfaceMuted,
    pageSwitchSelectedBorder: CORE_TOKENS.color.brandPrimaryStrong,
    pageSwitchUnselectedBorder: CORE_TOKENS.color.borderSubtle,
    pageSwitchText: '#666666',
  },
  spacing: {
    pagePaddingH: COMPONENT_TOKENS.page.paddingH,
    pagePaddingV: COMPONENT_TOKENS.page.paddingV,
    containerPaddingH: 0,
    containerPaddingV: 0,
    itemGap: 24,
    cardInnerPaddingH: 14,
    cardInnerPaddingV: 12,
    titleGap: 8,
    leftGroupMarginRight: 8,
    centerSubtitleMarginTop: 4,
    rightPillPaddingH: COMPONENT_TOKENS.controlTitle.rightPillPaddingH,
    rightPillPaddingV: COMPONENT_TOKENS.controlTitle.rightPillPaddingV,
    switchTrackPaddingH: 4,
    circleButtonLabelMarginTop: 4,
    pageSwitchPillPaddingH: COMPONENT_TOKENS.pageSwitch.paddingH,
    equipmentPaddingTop: COMPONENT_TOKENS.page.equipmentPaddingTop,
    equipmentPaddingVertical: COMPONENT_TOKENS.page.equipmentPaddingVertical,
  },
  radius: {
    card: CORE_TOKENS.radius.lg,
    pill: CORE_TOKENS.radius.full,
    circle: CORE_TOKENS.radius.full,
    pageSwitchPill: COMPONENT_TOKENS.pageSwitch.borderRadius,
  },
  sizes: {
    controlTitleHeight: COMPONENT_TOKENS.controlTitle.height,
    controlTitleCenterHeight: COMPONENT_TOKENS.controlTitle.centerHeight,
    controlTitleCenterHeightWithSubtitle: COMPONENT_TOKENS.controlTitle.centerHeightWithSubtitle,
    switchTrackWidth: CORE_TOKENS.size.switchTrackWidth,
    switchThumbSize: CORE_TOKENS.size.switchThumb,
    dividerWidth: COMPONENT_TOKENS.controlTitle.dividerWidth,
    dividerHeight: COMPONENT_TOKENS.controlTitle.dividerHeight,
    circleButtonSize: CORE_TOKENS.size.circleButton,
    circleButtonIconSize: CORE_TOKENS.size.iconMd,
    circleButtonItemWidth: COMPONENT_TOKENS.circleButtonGroup.itemWidth,
    circleButtonItemHeight: COMPONENT_TOKENS.circleButtonGroup.itemHeight,
    switchCardHeight: 80,
    pageSwitchPillHeight: COMPONENT_TOKENS.pageSwitch.height,
  },
  fontSize: {
    ExtraLarge: CORE_TOKENS.typography.titleXL,
    large: CORE_TOKENS.typography.titleMD,
    medium: CORE_TOKENS.typography.bodySM,
    small: CORE_TOKENS.typography.caption,
    pageSwitchPill: COMPONENT_TOKENS.pageSwitch.textSize,
  },
  motion: CORE_TOKENS.motion,
} as const;
